import { VNID } from "neolace/deps/vertex-framework.ts";
import { EntryTypeColor, PropertyMode, PropertyType, SiteSchemaData } from "neolace/deps/neolace-api.ts";

// Type helper to ensure that the schema is a valid SiteSchemaData without
// collapsing the type down to just "SiteSchemaData"
function ValidateSiteSchema<X extends SiteSchemaData>(x: X): X {
    return x;
}

// Import the schema:
export const schema = ValidateSiteSchema({
    entryTypes: {
        "_ETDIVISION": {
            id: VNID("_ETDIVISION"),
            name: "Division",
            description:
                "A division (also called Phylum outside of botany) is the main taxonomic classification within the Plant Kingdom.",
            friendlyIdPrefix: "d-",
            color: EntryTypeColor.Red,
            abbreviation: "D",
            enabledFeatures: {},
        },
        "_ETCLASS": {
            id: VNID("_ETCLASS"),
            name: "Class",
            description: "A class is a level of taxonomic classification between Division/Phylum and Order.",
            friendlyIdPrefix: "c-",
            color: EntryTypeColor.Violet,
            abbreviation: "C",
            enabledFeatures: {},
        },
        "_ETORDER": {
            id: VNID("_ETORDER"),
            name: "Order",
            description: "An order is a level of taxonomic classification between Class and Family.",
            friendlyIdPrefix: "o-",
            color: EntryTypeColor.Orange,
            abbreviation: "O",
            enabledFeatures: {},
        },
        "_ETFAMILY": {
            id: VNID("_ETFAMILY"),
            name: "Family",
            description: "A family is a level of taxonomic classification between Order and Genus.",
            friendlyIdPrefix: "f-",
            color: EntryTypeColor.Cyan,
            abbreviation: "F",
            enabledFeatures: {},
        },
        "_ETGENUS": {
            id: VNID("_ETGENUS"),
            name: "Genus",
            description: "A genus is a level of taxonomic classification between Family and Species.",
            friendlyIdPrefix: "g-",
            color: EntryTypeColor.Emerald,
            abbreviation: "G",
            enabledFeatures: {},
        },
        "_ETSPECIES": {
            id: VNID("_ETSPECIES"),
            name: "Species",
            description: "A species is a basic unit of classifying life.",
            friendlyIdPrefix: "s-",
            color: EntryTypeColor.Blue,
            abbreviation: "S",
            enabledFeatures: {
                Article: {},
                HeroImage: {
                    lookupExpression: `this.get(prop=[[/prop/_hasHeroImage]])`,
                },
            },
        },
        "_ETPLANTPART": {
            id: VNID("_ETPLANTPART"),
            name: "Plant Part",
            description: "Describes a part of a plant.",
            friendlyIdPrefix: "pp-",
            color: EntryTypeColor.Yellow,
            abbreviation: "PP",
            enabledFeatures: {},
        },
        "_ETIMAGE": {
            id: VNID("_ETIMAGE"),
            name: "Image",
            description: "An image, such as a photo of a plant",
            friendlyIdPrefix: "img-",
            color: EntryTypeColor.Slate,
            abbreviation: "IM",
            enabledFeatures: {
                Image: {},
            },
        },
    },
    properties: {
        "_parentTaxon": {
            id: VNID("_parentTaxon"),
            name: "Parent taxon",
            type: PropertyType.RelIsA,
            mode: PropertyMode.Optional,
            appliesTo: [],
            descriptionMD: `The parent taxon of this entry.`,
            rank: 0,
        },
        "_parentDivision": {
            id: VNID("_parentDivision"),
            isA: [VNID("_parentTaxon")], // This is a more specific "parent taxon" property
            name: "Division",
            type: PropertyType.RelIsA,
            appliesTo: [{ entryType: VNID("_ETCLASS") }],
            valueConstraint: `(targetEntry -> targetEntry.type() = entryType("_ETDIVISION"))`,
            mode: PropertyMode.Required,
            descriptionMD: `The parent division of this class.`,
            rank: 0,
        },
        "_parentClass": {
            id: VNID("_parentClass"),
            isA: [VNID("_parentTaxon")], // This is a more specific "parent taxon" property
            name: "Class",
            type: PropertyType.RelIsA,
            appliesTo: [{ entryType: VNID("_ETORDER") }],
            valueConstraint: `(targetEntry -> targetEntry.type() = entryType("_ETCLASS"))`,
            mode: PropertyMode.Required,
            descriptionMD: `The parent class of this order.`,
            rank: 0,
        },
        "_parentOrder": {
            id: VNID("_parentOrder"),
            isA: [VNID("_parentTaxon")], // This is a more specific "parent taxon" property
            name: "Order",
            type: PropertyType.RelIsA,
            appliesTo: [{ entryType: VNID("_ETFAMILY") }],
            valueConstraint: `(targetEntry -> targetEntry.type() = entryType("_ETORDER"))`,
            mode: PropertyMode.Required,
            descriptionMD: `The parent order of this family.`,
            rank: 0,
        },
        "_parentFamily": {
            id: VNID("_parentFamily"),
            isA: [VNID("_parentTaxon")], // This is a more specific "parent taxon" property
            name: "Family",
            type: PropertyType.RelIsA,
            appliesTo: [{ entryType: VNID("_ETGENUS") }],
            valueConstraint: `(targetEntry -> targetEntry.type() = entryType("_ETFAMILY"))`,
            mode: PropertyMode.Required,
            descriptionMD: `The parent family of this genus.`,
            rank: 0,
        },
        "_parentGenus": {
            id: VNID("_parentGenus"),
            isA: [VNID("_parentTaxon")], // This is a more specific "parent taxon" property
            name: "Genus",
            type: PropertyType.RelIsA,
            appliesTo: [{ entryType: VNID("_ETSPECIES") }],
            valueConstraint: `(targetEntry -> targetEntry.type() = entryType("_ETGENUS"))`,
            mode: PropertyMode.Required,
            descriptionMD: `The parent genus of this species.`,
            rank: 0,
        },
        "_divClasses": {
            id: VNID("_divClasses"),
            name: "Classes",
            type: PropertyType.RelOther,
            appliesTo: [{ entryType: VNID("_ETDIVISION") }],
            mode: PropertyMode.Auto,
            default: `this.reverse(prop=[[/prop/_parentDivision]])`,
            descriptionMD: `Classes that are part of this division.`,
            rank: 3,
        },
        "_classOrders": {
            id: VNID("_classOrders"),
            name: "Orders",
            type: PropertyType.RelOther,
            appliesTo: [{ entryType: VNID("_ETCLASS") }],
            mode: PropertyMode.Auto,
            default: `this.reverse(prop=[[/prop/_parentClass]])`,
            descriptionMD: `Orders that are part of this class.`,
            rank: 3,
        },
        "_orderFamilies": {
            id: VNID("_orderFamilies"),
            name: "Families",
            type: PropertyType.RelOther,
            appliesTo: [{ entryType: VNID("_ETORDER") }],
            mode: PropertyMode.Auto,
            default: `this.reverse(prop=[[/prop/_parentOrder]])`,
            descriptionMD: `Families that are part of this order.`,
            rank: 3,
        },
        "_familyGenera": {
            id: VNID("_familyGenera"),
            name: "Genera",
            type: PropertyType.RelOther,
            appliesTo: [{ entryType: VNID("_ETFAMILY") }],
            mode: PropertyMode.Auto,
            default: `this.reverse(prop=[[/prop/_parentFamily]])`,
            descriptionMD: `Genera (genuses) that are part of this family.`,
            rank: 3,
        },
        "_genusSpecies": {
            id: VNID("_genusSpecies"),
            name: "Species",
            type: PropertyType.RelOther,
            appliesTo: [{ entryType: VNID("_ETGENUS") }],
            mode: PropertyMode.Auto,
            default: `this.reverse(prop=[[/prop/_parentGenus]])`,
            descriptionMD: `Species that are part of this genus.`,
            rank: 3,
        },
        "_taxonomy": {
            id: VNID("_taxonomy"),
            name: "Taxonomy",
            type: PropertyType.RelOther,
            appliesTo: [
                { entryType: VNID("_ETCLASS") },
                { entryType: VNID("_ETDIVISION") },
                { entryType: VNID("_ETFAMILY") },
                { entryType: VNID("_ETGENUS") },
                { entryType: VNID("_ETORDER") },
                { entryType: VNID("_ETSPECIES") },
            ],
            mode: PropertyMode.Auto,
            default: `this.ancestors()`,
            descriptionMD: `The full taxonomy of this PlantDB entry.`,
            rank: 5,
        },
        // An image RELATES TO [an entry]
        "_imgRelTo": {
            id: VNID("_imgRelTo"),
            name: "Relates to",
            type: PropertyType.RelOther,
            appliesTo: [{ entryType: VNID("_ETIMAGE") }],
            valueConstraint:
                `(targetEntry -> targetEntry.type() in [entryType("_ETCLASS"), entryType("_ETDIVISION"), entryType("_ETFAMILY"), entryType("_ETGENUS"), entryType("_ETORDER"), entryType("_ETPLANTPART"), entryType("_ETSPECIES")])`,
            mode: PropertyMode.Recommended,
            descriptionMD: `Lists PlantDB entries that this images relates to.`,
            rank: 8,
        },
        // Related images
        "_relImages": {
            id: VNID("_relImages"),
            name: "Related images",
            type: PropertyType.RelOther,
            appliesTo: [
                { entryType: VNID("_ETCLASS") },
                { entryType: VNID("_ETDIVISION") },
                { entryType: VNID("_ETFAMILY") },
                { entryType: VNID("_ETGENUS") },
                { entryType: VNID("_ETORDER") },
                { entryType: VNID("_ETPLANTPART") },
                { entryType: VNID("_ETSPECIES") },
            ],
            mode: PropertyMode.Auto,
            default: `this.andDescendants().reverse(prop=[[/prop/_imgRelTo]]).image(format="thumb")`,
            descriptionMD: `Images related to this entry.`,
            rank: 10,
        },
        // Has hero image
        "_hasHeroImage": {
            id: VNID("_hasHeroImage"),
            name: "Has hero image",
            type: PropertyType.RelOther,
            appliesTo: [
                { entryType: VNID("_ETCLASS") },
                { entryType: VNID("_ETDIVISION") },
                { entryType: VNID("_ETFAMILY") },
                { entryType: VNID("_ETGENUS") },
                { entryType: VNID("_ETORDER") },
                { entryType: VNID("_ETPLANTPART") },
                { entryType: VNID("_ETSPECIES") },
            ],
            mode: PropertyMode.Recommended,
            descriptionMD: `Hero image used for this entry`,
            rank: 60,
        },
        // Has part
        "_hasPart": {
            id: VNID("_hasPart"),
            name: "Has part",
            type: PropertyType.RelOther,
            appliesTo: [
                { entryType: VNID("_ETCLASS") },
                { entryType: VNID("_ETDIVISION") },
                { entryType: VNID("_ETFAMILY") },
                { entryType: VNID("_ETGENUS") },
                { entryType: VNID("_ETORDER") },
                { entryType: VNID("_ETSPECIES") },
            ],
            mode: PropertyMode.Optional,
            valueConstraint: `(targetEntry -> targetEntry.type() = entryType("_ETPLANTPART"))`,
            descriptionMD: `This [species/genus/etc.] has this part(s).`,
            rank: 10,
            inheritable: true,
            enableSlots: true,
        },
        // Plant part is found in
        "_partFoundIn": {
            id: VNID("_partFoundIn"),
            name: "Found in",
            type: PropertyType.RelOther,
            appliesTo: [{ entryType: VNID("_ETPLANTPART") }],
            mode: PropertyMode.Auto,
            default: `this.andDescendants().reverse(prop=[[/prop/_hasPart]])`,
            descriptionMD: `This plant part is found in these species/genera/etc.`,
            rank: 10,
        },
        // Plant part is a type of plant part
        "_partIsAPart": {
            id: VNID("_partIsAPart"),
            name: "Is a",
            type: PropertyType.RelIsA,
            appliesTo: [{ entryType: VNID("_ETPLANTPART") }],
            mode: PropertyMode.Recommended,
            descriptionMD: `The more general class of this plant part.`,
            rank: 0,
        },
        "_partHasTypes": {
            id: VNID("_partHasTypes"),
            name: "Has types",
            type: PropertyType.RelOther,
            appliesTo: [{ entryType: VNID("_ETPLANTPART") }],
            mode: PropertyMode.Auto,
            default: `this.reverse(prop=[[/prop/_partIsAPart]])`,
            descriptionMD: `Sub-types of this plant part`,
            rank: 3,
        },
        ////////////////////////////////////////////////////////////////////////////////////////
        ///////// Value properties:

        // A plant's scientific name
        "_propScientificName": {
            id: VNID("_propScientificName"),
            name: "Scientific name",
            type: PropertyType.Value,
            appliesTo: [{ entryType: VNID("_ETSPECIES") }],
            mode: PropertyMode.Required,
            descriptionMD:
                "The **scientific name**, sometimes called the **binomial name** or **latin name** is an unambiguous species identifier.",
            rank: 3,
            displayAs: "*{value}*",
        },
        // An entry's Wikidata Entry ID
        "_propWikidataQID": {
            id: VNID("_propWikidataQID"),
            name: "Wikidata Item ID",
            type: PropertyType.Value,
            appliesTo: [
                { entryType: VNID("_ETCLASS") },
                { entryType: VNID("_ETDIVISION") },
                { entryType: VNID("_ETFAMILY") },
                { entryType: VNID("_ETGENUS") },
                { entryType: VNID("_ETORDER") },
                { entryType: VNID("_ETSPECIES") },
            ],
            mode: PropertyMode.Optional,
            descriptionMD: "ID of this item on Wikidata, the free knowledge base that anyone can edit.",
            rank: 15,
            displayAs: "[{value}](https://www.wikidata.org/wiki/{value})",
        },
        // Other names for a plant
        "_propOtherNames": {
            id: VNID("_propOtherNames"),
            name: "Other names",
            type: PropertyType.Value,
            appliesTo: [{ entryType: VNID("_ETSPECIES") }],
            mode: PropertyMode.Optional,
            descriptionMD: "Other common names for this species.",
            rank: 5,
        },
    },
});
