entryTypes:
  - id: _ET_TUTORIAL
    name: Tutorial
    description: ''
    friendlyIdPrefix: t-
    color: cyan
    abbreviation: T
    enabledFeatures:
      Article: {}
  - id: _ET_GUIDE
    name: Guide
    description: ''
    friendlyIdPrefix: guide-
    color: indigo
    abbreviation: G
    enabledFeatures:
      Article: {}
  - id: _ET_EXPLANATION
    name: Explanation
    description: ''
    friendlyIdPrefix: ''
    color: orange
    abbreviation: EX
    enabledFeatures:
      Article: {}
  - id: _ET_REFERENCE
    name: Reference
    description: ''
    friendlyIdPrefix: ''
    color: red
    abbreviation: R
    enabledFeatures:
      Article: {}
  - id: _ET_TERM
    name: Term
    description: A definition of a term
    friendlyIdPrefix: term-
    color: yellow
    abbreviation: T
    enabledFeatures: {}
  - id: _ET_IMAGE
    name: Image
    description: An Image
    friendlyIdPrefix: img-
    color: ''
    abbreviation: ''
    enabledFeatures:
      Image: {}
properties: []
idMap:
  comment: >-
    if you edit one of the IDs above, you should edit it below here too. You do
    not need to add IDs here for new entries.
  map:
    _ET_TUTORIAL: _3KfITp6uvx66i4vJkAFcIy
    _ET_GUIDE: _4G0fpJp3q3gDPeFdEu3BD6
    _ET_EXPLANATION: _7TZIMnSQGqTSn1g1Y7jANc
    _ET_REFERENCE: _2LjABVq2j7Ae1mOVwiJJiN
    _ET_TERM: _5oX5jvGNB6hQzuu08iQs5b
    _ET_IMAGE: _35IUfcCgWAq8y6uRJ2zY29
