name: Check types (backend)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.x

      - name: Check types and cache dependencies (backend)
        run: deno cache --import-map=import_map.json --unstable neolace/api/server.ts
        working-directory: ./backend
