name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  deno-version: v1.16.x

jobs:
  validate:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/validate-code.yml@${{ github.ref }}
    with:
      deno-version: ${{ env.deno-version }}
