name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  deno-version: v1.16.x

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/validate-code.yml@${{ github.sha }}
        with:
          deno-version: ${{ env.deno-version }}
