name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  deno-version: v1.16.x

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:

      - name: Setup repo
        uses: actions/checkout@v2

      - uses: ./.github/workflows/validate-code.yml
        with:
          deno-version: ${{ env.deno-version }}
