name: Run tests (backend)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.x

      # TODO: Start docker-compose

      - name: Run neolace database servers
        run: docker-compose -f "docker-compose.yml" up -d

      - name: Wait for Neo4j
        run: sleep 10

      - name: Test Suite setup (backend)
        run: deno run --import-map=import_map.json --allow-net --allow-read --allow-env --allow-write --unstable neolace/scripts/test-setup.ts
        working-directory: ./backend

      - name: Run tests (backend)
        run: deno test --import-map=import_map.json --allow-net --allow-env --allow-read --unstable
        working-directory: ./backend

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
