name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.x

      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter (backend)
        run: deno lint
        working-directory: ./backend

      - name: Run linter (API)
        run: deno lint src
        working-directory: ./neolace-api

      - name: Run linter (frontend)
        run: deno lint components pages lib
        working-directory: ./frontend

  check-backend-types:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.x

      - name: Check types and cache dependencies (backend)
        run: deno cache --import-map=import_map.json --unstable neolace/api/server.ts
        working-directory: ./backend

      # Type checking the test suite is very slow we do it asynchronously now too, while the actual tests themselves run in a separate job

      - name: Type check test suite setup
        run: deno cache --import-map=import_map.json --unstable neolace/scripts/test-setup.ts
        working-directory: ./backend

      - name: Type check tests
        env:
          ENV_TYPE: test
        run: deno test --import-map=import_map.json --no-run --unstable
        working-directory: ./backend

  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.x

      - name: Run neolace database servers
        run: docker-compose -f "docker-compose.yml" up -d

      - name: Wait for Neo4j
        run: sleep 10

      - name: Test Suite setup (backend)
        env:
          ENV_TYPE: test
        run: deno run --import-map=import_map.json --allow-net --allow-read --allow-env --allow-write --unstable --no-check neolace/scripts/test-setup.ts
        working-directory: ./backend

      - name: Run tests (backend)
        env:
          ENV_TYPE: test
        run: deno test --import-map=import_map.json --allow-net --allow-env --allow-read --unstable --no-check
        working-directory: ./backend

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
